# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10 or 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"  # You can change this to "3.10" if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "requirements.txt not found, skipping..."
        pip install flake8 pytest  # Always install linting and testing tools

    - name: Lint with flake8
      run: |
        # Lint with flake8, using custom config file if present
        flake8 . --config=setup.cfg --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --config=setup.cfg --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Run tests with pytest, using custom configuration if present
        pytest --maxfail=3 --disable-warnings --config=pytest.ini
